FleaMarketMS/Controllers/ManagerController.cs
using MES.Models;
using MES.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MESIII;
using System.Text;

namespace FleaMarketMS.Controllers
{
    public class ManagerController : BaseController
    {
        //
        // GET: /Manager/

        public ActionResult Index()
        {
            return View();
        }

        #region //ActionResult

        public ActionResult ProgramInfo(UserModel userModel)
        {
            userModel.CURR_DOMAIN = "";
            userModel.CURR_PACKAGE = "管理";
            userModel.CURR_PROGRAM = "功能模块";
            return View(userModel);
        }

        public ActionResult StatusInfo(UserModel userModel)
        {
            userModel.CURR_DOMAIN = "";
            userModel.CURR_PACKAGE = "管理";
            userModel.CURR_PROGRAM = "状态管理";
            return View(userModel);
        }

        public ActionResult TypeInfo(UserModel userModel)
        {
            userModel.CURR_DOMAIN = "";
            userModel.CURR_PACKAGE = "管理";
            userModel.CURR_PROGRAM = "类型管理";
            return View(userModel);
        }

        public ActionResult RoleInfo(UserModel userModel)
        {
            userModel.CURR_DOMAIN = "";
            userModel.CURR_PACKAGE = "管理";
            userModel.CURR_PROGRAM = "角色管理";
            return View(userModel);
        }

        public ActionResult UserInfo(UserModel userModel)
        {
            userModel.CURR_DOMAIN = "";
            userModel.CURR_PACKAGE = "管理";
            userModel.CURR_PROGRAM = "用户管理";
            return View(userModel);
        }

        public ActionResult SenseWord(UserModel userModel)
        {
            userModel.CURR_DOMAIN = "";
            userModel.CURR_PACKAGE = "管理";
            userModel.CURR_PROGRAM = "词语管理";
            return View(userModel);
        }
        #endregion

        public ActionResult Category(UserModel userModel)
        {
            userModel.CURR_DOMAIN = "";
            userModel.CURR_PACKAGE = "管理";
            userModel.CURR_PROGRAM = "物品类别管理";
            return View(userModel);
        }

        public ActionResult PostHistory(UserModel userModel)
        {
            userModel.CURR_DOMAIN = "";
            userModel.CURR_PACKAGE = "管理";
            userModel.CURR_PROGRAM = "发布历史";

            int PAGE_INDEX = 1;
            if (Request["PAGE_INDEX"] != null) { int.TryParse(Request["PAGE_INDEX"], out PAGE_INDEX); }
            string sParam = "<root><PostMsg>";
            sParam += "<MsgID>-1</MsgID>";
            sParam += "<UserID>" + Session["USER_ID"].ToString() + "</UserID>";
            sParam += "<CategoryID>-1</CategoryID>";
            sParam += "<Title></Title>";
            sParam += "<MsgContent></MsgContent>";
            sParam += "<PictureSrc></PictureSrc>";
            sParam += "<StatusNO>A</StatusNO>";
            sParam += "</PostMsg>";
            sParam += "<PAGE_INFO>";
            sParam += "<PAGE_INDEX>" + PAGE_INDEX + "</PAGE_INDEX>";
            sParam += "<PAGE_SIZE>20</PAGE_SIZE>";
            sParam += "<ORDER_BY>a.AddDateTime DESC</ORDER_BY>";
            sParam += "</PAGE_INFO>";
            sParam += "</root>";
            DataSet oDS = client.ctEnumerateData("ManagerSO.QryPostMsg002", sParam);
            IEnumerable<PostMsg> postMsgls = oDS.Tables["QryPostMsg002"].TabeToList<PostMsg>();
            ViewBag.PostMstLst = postMsgls;

            return View(userModel);
        }

        public ActionResult Review(UserModel userModel)
        {
            userModel.CURR_DOMAIN = "";
            userModel.CURR_PACKAGE = "管理";
            userModel.CURR_PROGRAM = "信息审核";
            return View(userModel);
        }

        public ActionResult Attention(UserModel userModel)
        {
            userModel.CURR_DOMAIN = "";
            userModel.CURR_PACKAGE = "管理";
            userModel.CURR_PROGRAM = "关注信息";
            return View(userModel);
        }

        public ActionResult Search(UserModel userModel)
        {
            userModel.CURR_DOMAIN = "";
            userModel.CURR_PACKAGE = "管理";
            userModel.CURR_PROGRAM = "搜索";
            return View(userModel);
        }

        [HttpGet]
        public ActionResult UserInfoSelf(UserModel userModel)
        {
            string sParam = "<root><UserInfo>";
            sParam += "<UserID>" + Session["USER_ID"].ToString() + "</UserID>";
            sParam += "<UserNO></UserNO>";
            sParam += "<UserName></UserName>";
            sParam += "<MobilePhone></MobilePhone>";
            sParam += "<PassWD></PassWD>";
            sParam += "<Email></Email>";
            sParam += "<IconSrc></IconSrc>";
            sParam += "<RoleCollect></RoleCollect>";
            sParam += "<LastLoginTime></LastLoginTime>";
            sParam += "<LastLoginIP></LastLoginIP>";
            sParam += "<LoginCount>-1</LoginCount>";
            sParam += "<RoleCollect>-1</RoleCollect>";
            sParam += "<TypeNO></TypeNO>";
            sParam += "<StatusNO>A</StatusNO>";
            sParam += "</UserInfo>";
            sParam += "<PAGE_INFO>";
            sParam += "<PAGE_INDEX>-1</PAGE_INDEX>";
            sParam += "<PAGE_SIZE>-1</PAGE_SIZE>";
            sParam += "<ORDER_BY></ORDER_BY>";
            sParam += "</PAGE_INFO>";
            sParam += "</root>";
            DataSet oDS = client.ctEnumerateData("ManagerSO.QryUserInfo001", sParam);
            if (cmn.CheckEOF(oDS))
            {
                ViewBag.UserID = cmn.cap_int(oDS.Tables[0].Rows[0]["UserID"]);
                ViewBag.UserNO = cmn.cap_string(oDS.Tables[0].Rows[0]["UserNO"]);
                ViewBag.IconSrc = cmn.cap_string(oDS.Tables[0].Rows[0]["IconSrc"]);
                ViewBag.UserName = cmn.cap_string(oDS.Tables[0].Rows[0]["UserName"]);
                ViewBag.MobilePhone = cmn.cap_string(oDS.Tables[0].Rows[0]["MobilePhone"]);
                ViewBag.Email = cmn.cap_string(oDS.Tables[0].Rows[0]["Email"]);
                ViewBag.IsValidate = cmn.cap_int(oDS.Tables[0].Rows[0]["IsValidate"]);
            }

            userModel.CURR_DOMAIN = "";
            userModel.CURR_PACKAGE = "管理";
            userModel.CURR_PROGRAM = "个人信息";
            return View(userModel);
        }

        [HttpPost]
        public ActionResult UserInfoSelf()
        {
            string sParam = "";
            try
            {
                string UserID = Request.Form["UserID"];
                string UserNO = Request.Form["UserNO"];
                string UserName = Request.Form["txtUserName"];
                string MobilePhone = Request.Form["txtMobilePhone"];
                string Email = Request.Form["txtEmail"];
                string IconSrc = Request.Form["txtIconSrc"];
                if (Request.Files[0].ContentLength>0)
                {
                    
                    Request.Files[0].SaveAs(Server.MapPath("~/assets/userIcon/" + UserNO + "." + Request.Files[0].FileName.Split('.')[1]));
                    IconSrc = UserNO + "." + Request.Files[0].FileName.Split('.')[1];
                }

                sParam = "<root><UserInfo>";
                sParam += "<UserID>" + UserID + "</UserID>";
                sParam += "<UserNO>" + UserNO + "</UserNO>";
                sParam += "<UserName>" + UserName + "</UserName>";
                sParam += "<MobilePhone>" + MobilePhone + "</MobilePhone>";
                sParam += "<Email>" + Email + "</Email>";
                sParam += "<IconSrc>" + IconSrc + "</IconSrc>";
                sParam += "</UserInfo></root>";
                nResult = client.ctPostTxact("ManagerSO.TxUserInfo001", sParam, TxTypeConsts.TxTypeUpdate);
            }
            catch (Exception e1)
            {
                userModel.MESSAGE = e1.Message;
                string error_message = Microsoft.JScript.GlobalObject.escape(e1.Message);
                res = "{\"status\" : \"error\",\"msg\": \"error\",\"error_desc\":\"" + error_message + "\"}";
                return Content(res);
            }

            sParam = "<root><UserInfo>";
            sParam += "<UserID>" + Session["USER_ID"].ToString() + "</UserID>";
            sParam += "<UserNO></UserNO>";
            sParam += "<UserName></UserName>";
            sParam += "<MobilePhone></MobilePhone>";
            sParam += "<PassWD></PassWD>";
            sParam += "<Email></Email>";
            sParam += "<IconSrc></IconSrc>";
            sParam += "<RoleCollect></RoleCollect>";
            sParam += "<LastLoginTime></LastLoginTime>";
            sParam += "<LastLoginIP></LastLoginIP>";
            sParam += "<LoginCount>-1</LoginCount>";
            sParam += "<RoleCollect>-1</RoleCollect>";
            sParam += "<TypeNO></TypeNO>";
            sParam += "<StatusNO>A</StatusNO>";
            sParam += "</UserInfo>";
            sParam += "<PAGE_INFO>";
            sParam += "<PAGE_INDEX>-1</PAGE_INDEX>";
            sParam += "<PAGE_SIZE>-1</PAGE_SIZE>";
            sParam += "<ORDER_BY></ORDER_BY>";
            sParam += "</PAGE_INFO>";
            sParam += "</root>";
            DataSet oDS = client.ctEnumerateData("ManagerSO.QryUserInfo001", sParam);
            if (cmn.CheckEOF(oDS))
            {
                ViewBag.UserID = cmn.cap_int(oDS.Tables[0].Rows[0]["UserID"]);
                ViewBag.UserNO = cmn.cap_string(oDS.Tables[0].Rows[0]["UserNO"]);
                ViewBag.IconSrc = cmn.cap_string(oDS.Tables[0].Rows[0]["IconSrc"]);
                ViewBag.UserName = cmn.cap_string(oDS.Tables[0].Rows[0]["UserName"]);
                ViewBag.MobilePhone = cmn.cap_string(oDS.Tables[0].Rows[0]["MobilePhone"]);
                ViewBag.Email = cmn.cap_string(oDS.Tables[0].Rows[0]["Email"]);
                ViewBag.UserNO = cmn.cap_string(oDS.Tables[0].Rows[0]["UserNO"]);
                ViewBag.IsValidate = cmn.cap_int(oDS.Tables[0].Rows[0]["IsValidate"]);
            }

FleaMarketMS/Views/Shared/Header.cshtml
@model MES.Models.UserModel
@using System.Data;
@using System.Xml;
@using MES.Services;
@using MESIII;

<header class="header navbar navbar-fixed-top" role="banner">
    <div class="container">
        <ul class="nav navbar-nav">
            <li class="nav-toggle">
                <a href="javascript:void(0);" title=""><i class="icon-reorder"></i></a>
            </li>
        </ul>
        <div id="HeaderTool">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")" style="height: 48px;">
                <img src="@Url.Content("~/assets/img/logo.gif")" alt="logo" />
                <strong>实时二手信息</strong>
            </a>
            <a href="#" class="toggle-sidebar bs-tooltip" data-placement="bottom" data-original-title="菜单展合">
                <i class="icon-reorder"></i>
            </a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown user">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    @{string userpath = ""; if (Session["UserIcon"] == null) { userpath = "default.png"; } else { userpath = Session["UserIcon"].ToString(); }}
                <i><img class="userIcon" src="~/assets/userIcon/@userpath" /></i>
                @if (Session["UserName"] != null)
                {
                    <span class="username">@Session["UserName"].ToString()</span>
                }
                else
                {
                    <span class="username"></span>
                }
                <i class="icon-caret-down small"></i>
            </a>
            <ul class="dropdown-menu" id="userMenu">
                @if (Session["UserName"] == null)
                {
                    <li><a href="#" data-toggle="modal" data-target="#modalLogin"><i class="icon-signin"></i>登陆</a></li>
                    <li><a href="#"><i class="icon-pencil"></i>注册</a></li>
                }
                else
                {
                    <li><a href="#" id="PostMsg"><i class="icon-user"></i>发表</a></li>
                    <li><a href="@Url.Action("PostHistory","Manager")"><i class="icon-user-md"></i>个人中心</a></li>
                    <li class="divider"></li>
                    <li><a href="javascript:cap_logout();"><i class="icon-key"></i>退出</a></li>
                }
            </ul>
        </li>
    </ul>
</div>
</header>

FleaMarketMS/Views/Shared/HeaderFront.cshtml
@model MES.Models.UserModel
@using System.Data;
@using System.Xml;
@using MES.Services;
@using MESIII;
@{
    //var TARGET_DOMAIN = Model.CURR_DOMAIN;
    ////var TARGET_DOMAIN_NAME = CommonService.GetDomainName(Session["USER_DOMAIN"].ToString(), TARGET_DOMAIN);
    //var TARGET_PACK = Model.CURR_PACKAGE;
    //var TARGET_PRO = Model.CURR_PROGRAM;

    //XmlDocument oUserPackage = new XmlDocument();
    //oUserPackage.LoadXml(Session["USER_DOMAIN"].ToString());
    //XmlNodeList ns = oUserPackage.SelectNodes("//root/USER_DOMAIN");

    //XmlDocument xmldoc = (XmlDocument)ViewData["GUI_DATA"];
    //XmlDocument xmlError = (XmlDocument)ViewData["ERROR_DATA"];
    //var PART = TARGET_DOMAIN + "Domain";

}
<header class="header navbar navbar-fixed-top" role="banner">
    <div class="container">
        <div id="HeaderTool">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")" style="height: 48px;">
                <img src="@Url.Content("~/assets/img/logo.gif")" alt="logo" />
                <strong>实时二手信息</strong>
            </a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown user">
                <a href="#" id="userdrop" class="dropdown-toggle" data-toggle="dropdown">
                    @{string userpath = ""; if (Session["UserIcon"] == null) { userpath = "default.png"; } else { userpath = Session["UserIcon"].ToString(); }}
                    <i><img class="userIcon" src="~/assets/userIcon/@userpath" /></i>
                    @if (Session["UserName"] != null)
                    {
                        <span class="username">@Session["UserName"].ToString()</span>
                    }
                    else
                    {
                        <span class="username"></span>
                    }
                    <i class="icon-caret-down small"></i>
                </a>
                <ul class="dropdown-menu" id="userMenu">
                    @if (Session["UserName"] == null)
                    {
                        <li><a href="#" id='LoginBtn' data-toggle="modal"><i class="icon-signin"></i>登陆</a></li>
                        <li><a href="#" id="RegisterBtn"><i class="icon-pencil"></i>注册</a></li>
                    }
                    else
                    {
                        <li><a href="#" id="PostMsg"><i class="icon-user"></i>发表</a></li>
                        <li><a href="@Url.Action("PostHistory","Manager")"><i class="icon-user-md"></i>个人中心</a></li>
                        <li class="divider"></li>
                        <li><a href="javascript:cap_logout();"><i class="icon-key"></i>退出</a></li>
                    }
                </ul>
            </li>
        </ul>
    </div>
</header>

<!-- Modal登陆 -->
<div class="modal fade" id="modalLogin" tabindex="-1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">登 陆</h4>
            </div>
            <div class="modal-body">
                <form id="login_form" class=" form-horizontal">
                    <div class="form-group">
                        <label class="col-sm-4 col-md-2 control-label">账号<span class="required">*</span></label>
                        <div class="col-sm-6 col-md-8">
                            <input type="text" id="txtUserNO" name="txtUserNO" class="form-control required" placeholder="请输入账号" data-msg-required="请输入账号" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 col-md-2 control-label">密码<span class="required">*</span></label>
                        <div class="col-sm-6 col-md-8">
                            <input type="password" id="txtPassWD" name="txtPassWD" class="form-control required" placeholder="请输入密码" data-msg-required="请输入密码" />
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <span class="alert fade in alert-danger" style="display: none;"></span>
                <button type="button" id="login_close" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" id="login_confirm" class="btn btn-primary">登陆</button>
            </div>
        </div>
    </div>
</div>

<!-- 注册 -->
<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title edit">注 册</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" id="register-form" action="#">
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 control-label">账  号<span class="required">*</span></label>
                        <div class="col-sm-6 col-md-6">
                            <input type="text" maxlength="20" id="txtRegisterUserNO" name="txtUserNO" class="form-control required" placeholder="请输入账号" data-msg-required="请输入账号">
                        </div>
                        <div class="col-sm-3 col-md-3 control-label" style="display:none;color:red" id="txtRegisterUserNOError"></div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3  control-label">用户名<span class="required">*</span></label>
                        <div class="col-sm-6 col-md-6">
                            <input type="text" maxlength="50" id="txtRegisterUserName" name="txtUserName" class="form-control required" placeholder="请输入用户名" data-msg-required="请输入用户名">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 control-label">密  码<span class="required">*</span></label>
                        <div class="col-sm-6 col-md-6">
                            <input type="password" maxlength="50" id="txtRegisterPassWD" name="txtPassWD" class="form-control required" placeholder="请输入密码" data-msg-required="请输入密码">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-3 control-label">确认密码<span class="required">*</span></label>
                        <div class="col-sm-6 col-md-6">
                            <input type="password" maxlength="50" id="txtRegisterRePassWD" name="txtRePassWD" class="form-control required" placeholder="请确认密码" data-msg-required="请确认密码">
                        </div>
                        <div class="col-sm-3 col-md-3 control-label" style="display:none;color:red" id="txtRegisterPasswdError"></div>
                    </div>
                </form>
                <div class="alert fade in alert-danger" style="display: none;"></div>
            </div>
            <div class="modal-footer">
                <span class="alert-danger" id="registerError" style="display: none;"></span>
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" id="registerConfirm">确认</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<script>
    $(function () {
        $("#LoginBtn").click(function () {
            cap_clear("#login_form");
            $("#modalLogin .alert").hide().text('');
            $("#modalLogin").modal('show');
        });

        function loginIn(UserNO, Passwd) {
            if (typeof (UserNO) != 'undefined' && UserNO != '' && typeof (Passwd) != 'undefined' && Passwd != '') {
                $.ajax({
                    url: "@Url.Action("Login", "Home")",
                    type: "POST",
                    async: false,
                    dataType: "json",
                    data: {
                        UserNO: UserNO,
                        PassWD: Passwd
                    },
                    success: function (data, textStatus, xhr) {
                        if (data.msg == "success") {
                            $("#userMenu").children().remove();
                            var html = "<li><a href='#' data-toggle='modal' id='PostMSG'><i class='icon-user'></i>发表</a></li>";
                            html += "<li><a href=\"@Url.Action("PostHistory","Manager")\"><i class='icon-user-md'></i>个人中心</a></li>";
                            html += "<li class='divider'></li>";
                            html += " <li><a href=\"javascript:cap_logout();\"><i class='icon-key'></i>退出</a></li>";
                            $("#userMenu").append($(html));
                            $("#userdrop .userIcon").prop("src", data.usericon);
                            $("#userdrop .username").text(data.username);
                            $("#modalLogin").modal('hide');

                            $("#PostMSG").click(function () {
                                cap_clear("#PostMsg-form");
                                cap_category("@Url.Action("QryCategory001", "Manager")","#cboCategory","","CHOOSE");
                                $("#modalPostMSG").modal('show');
                                $("#modalPostMSG .modal-dialog").css("width",($(window).width())*0.9);
                            });
                        }
                        else if (data.msg == "fail") {
                            $("#modalLogin .alert").show().text('用户名或密码错误');
                        } else {
                            cap_alert(data.error_desc);
                        }
                    }
                });

            }
        }

        $("#login_confirm").click(function () {
            if ($("#login_form").valid()) {
                loginIn($("#txtUserNO").val(), $("#txtPassWD").val());
            }
        });

        $("#RegisterBtn").click(function () {
            cap_clear("#register-form");
            $("#txtRegisterUserNOError").text('').hide();
            $("#txtRegisterPasswdError").text('').hide();
            $("#registerError").text('').hide();
            $("#registerModal").modal('show');
        });


        $("#txtRegisterUserNO").focus(function () {
            $("#txtRegisterUserNOError").text('').hide();
        });
        $("#txtRegisterUserNO").blur(function () {
            if ($(this).val().length > 0) {
                $.ajax({
                    url: "@Url.Action("CheckUserNO", "Home")",
                    type: "POST",
                    async: false,
                    dataType: "json",
                    data: {
                        UserNO: $("#txtRegisterUserNO").val()
                    },
                    success: function (data) {
                        if (data.msg == "success") {
                            $("#txtRegisterUserNOError").text('').hide();
                        }
                        else if (data.msg == "fail") {
                            $("#txtRegisterUserNOError").show().text('已存在');
                        } else {
                            cap_alert(data.error_desc);
                        }
                    }
                });
            }
        });

        $("#txtRegisterRePassWD").focus(function () {
            $("#txtRegisterPasswdError").text('').hide();
        })
        $("#txtRegisterRePassWD").blur(function () {
            if ($("#txtRegisterPassWD").val() != $(this).val()) {
                $("#txtRegisterPasswdError").text('密码不一致').show();
            } else {
                $("#txtRegisterPasswdError").text('').hide();
            }
        });

        $("#registerConfirm").click(function () {
            if ($("#register-form").valid() && $("#txtRegisterUserNOError").text() == '' && $("#txtRegisterPasswdError").text() == '') {
                $.ajax({
                    url: "@Url.Action("RegisterUser", "Home")",
                    type: "POST",
                    async: false,
                    dataType: "json",
                    data: {
                        UserNO: $("#txtRegisterUserNO").val(),
                        UserName: $("#txtRegisterUserName").val(),
                        PassWD: $("#txtRegisterPassWD").val()
                    },
                    success: function (data, textStatus, xhr) {
                        if (data.msg == "success") {
                            $("#registerModal").modal('hide');
                            loginIn($("#txtRegisterUserNO").val(), $("#txtRegisterPassWD").val());
                        }
                        else {
                            $("#registerError").text(data.error_desc).show();
                        }
                    }
                });
            }
        });

    });

</script>

FleaMarketMS/Views/Shared/Menu.cshtml
@model MES.Models.UserModel
@using System.Data;
@using System.Xml;
@using MESIII;
@using System.Text.RegularExpressions;

@{
    CmnSrvLib cmn = new CmnSrvLib();

    XmlDocument oUserProgram = new XmlDocument();
    oUserProgram.LoadXml(Session["USER_PROGRAM"].ToString());
    XmlNodeList ns2 = oUserProgram.SelectNodes("//root/QryProgramInfo002");
}
<div id="sidebar" class="sidebar-fixed">
    <div id="sidebar-content">
        <ul id="nav" style="margin: 0px;">
            <li class="current open">
                <a href="javascript:void(0);"><i class="icon-desktop"></i>功能选项</a>
                <ul class="sub-menu">
                    @foreach (XmlNode node2 in ns2)
                    {
                        var path = node2.SelectSingleNode("Path").InnerText;
                        var PROGRAM_PACK = Regex.Match(path,"^/(\\w+)/(\\w+)$").Groups[1].Value;
                        var PROGRAM_NO = Regex.Match(path, "^/(\\w+)/(\\w+)$").Groups[2].Value;
                        var PROGRAM_NAME_CH = node2.SelectSingleNode("ProgramName").InnerText;
                        var PROGRAM_PATH = "";
                        var ACTIVE_FLAG = "";

                        PROGRAM_PATH = Url.Action(PROGRAM_NO, PROGRAM_PACK);
                        if(PROGRAM_PATH.Equals(Request.Path))
                        {
                            ACTIVE_FLAG = "current";
                        }
                        <li class="@ACTIVE_FLAG">
                            <a href="@PROGRAM_PATH"><i class="icon-angle-right"></i>@PROGRAM_NAME_CH</a>
                        </li>
                    }
                </ul>
            </li>
        </ul>
        <div class="sidebar-title">
            <span>
            </span>
        </div>
    </div>
    <div id="divider" class="resizeable"></div>
</div>

FleaMarketMS/Views/Shared/Title.cshtml
@model MES.Models.UserModel
   
<div class="crumbs">
    <ul id="breadcrumbs" class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            @Model.CURR_PACKAGE
        </li>
        <li>
            @Model.CURR_PROGRAM
        </li>
    </ul>
    <ul class="crumb-buttons">
        <li>
            <a>
                <i class="icon-calendar"></i>
                <span id="dtTimer"></span>
            </a>
        </li>        
    </ul>
</div>

<script>
    document.title = '跳蚤市场' + ' | @Model.CURR_PACKAGE | @Model.CURR_PROGRAM';
    $("#HeaderTool").show();
    $("#container").toggleClass("sidebar-open");
    //$('#dtTimer').html(new Date().Format("yyyy-MM-dd hh:mm:ss"));
    var displayTime = window.setInterval(function () {
        $('#dtTimer').html(new Date().Format("yyyy-MM-dd hh:mm:ss"));
    }, 1000);

</script>